# Generated by Django 2.2.5 on 2021-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_approved_status',
            field=models.BooleanField(default=False),
        ),
    ]
