# Generated by Django 2.2.5 on 2021-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0002_complaint_is_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_next_update_status',
            field=models.BooleanField(default=False),
        ),
    ]
