# Generated by Django 2.2.5 on 2021-05-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0004_policestation_email'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='police_station',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.PoliceStation'),
            preserve_default=False,
        ),
    ]
