# Generated by Django 2.2.5 on 2021-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0003_district_policestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
